export const medications: string[] = [
    "Motegrity",
    "Jornay",
    "Kerendia",
    "Methylphenidate HCL",
    "Methylphenidate",
    "MyFembree",
    "Repatha 140MG/ML",
    "Slynd",
    "Trintellix",
    "Xifaxan",
    "Gabapentin (Gralise)",
    "Adbry",
    "Adzenys",
    "Afrezza",
    "Aimovig",
    "Airsupra",
    "Annovera",
    "Austedo",
    "Azstarys",
    "Addyi",
    "Adlarity",
    "Ajovy",
    "Amitiza",
    "Amovig",
    "AndroGel",
    "Androderm",
    "Arazlo",
    "Arazlo (tazarotene) Lotion",
    "Arazlo Fabior Tazarotene Topical Cream",
    "Tazarotene Topical Foam",
    "Tazarotene Topical Gel",
    "Tazorac",
    "Auvelity",
    "Aveed Depo-Testosterone",
    "Testopel",
    "Testosterone Cypionate",
    "Testosterone Enanthate",
    "Xyosted",
    "Belbuca",
    "Bijuva",
    "Bonjesta",
    "Botox",
    "Breztri",
    "Briviact",
    "Briviact Inj",
    "Bronchitol",
    "Budeesonide",
    "Basaglar KwikPen",
    "Bydureon",
    "Caplyta",
    "Cequa",
    "Cosentyx",
    "Cyanocoblamin",
    "Cyltezo",
    "Calcineurin Inhibitor",
    "Caplyata",
    "Diclofenac 3% Gel",
    "Diclofenac Sodium 1.5% & 2%",
    "Dupixent",
    "Dyanavel",
    "Dexcom G6",
    "Dexcom G7",
    "Freestyle Libre 14 day",
    "Freestyle Libre 2 14 day",
    "Freestyle Libre 3",
    "Freestyle Libre 3 Plus",
    "Dyanavel XR",
    "Ecoza",
    "Emgality",
    "Epclusa",
    "Epogen",
    "Epclusa (Sofosbuvir/Velpatasvir)",
    "Eucrisa",
    "Eysuvis",
    "Focalin XR",
    "Farxiga",
    "Fasenra",
    "Gralise",
    "Gralise (Gabapentin Extended-release Tablet)",
    "Horizant (Gabapentin Enacarbil Extended-release Tablet)",
    "Lyrica (Pregabalin)",
    "Lyrica CR (Pregabalin Extended-release)",
    "Humira",
    "Hadlima 40 mg/0.4 mL",
    "Ibsrela (Tenapanor)",
    "Inpefa",
    "Ibsrela",
    "Intrarosa",
    "Invega Sustenna",
    "Iyuzeh",
    "Janumet/Janumet XR",
    "Jynarque",
    "Ubrelvy",
    "Jublia",
    "Kalydeco",
    "Kerydin",
    "Lokelma",
    "Lorazepam",
    "Lybalvi",
    "Lidoderm ZTLido",
    "Lupron",
    "Meibo",
    "Metformin",
    "Montelukast",
    "Montegrity",
    "Mavyret",
    "Modafinil 100MG Tablets",
    "Mounjaro",
    "Nurtec",
    "Opzelura",
    "Orilissa",
    "Orkambi",
    "Otezla",
    "Olumiant",
    "Ozempic",
    "Phexxi",
    "Procrit",
    "Provigil",
    "ProAir Digihaler",
    "Prolia",
    "Qelbree",
    "Quillichew",
    "Quviviq",
    "Qulipta",
    "Ramelteon",
    "Relistor",
    "Repatha",
    "Rinvoq",
    "Roflumilast",
    "Rybelsus",
    "Restasis",
    "Ryaltris",
    "Skyrizi",
    "Symdeko",
    "Saxenda",
    "Singulair Tabs and Chewables",
    "Spiriva Respimat",
    "Taltz",
    "Tazarotene",
    "Tacrolimus",
    "Topical Acne Products",
    "Topical Antifungals",
    "Trelegy Ellipta",
    "Tretinoin",
    "Trikafta",
    "Trintellix 10MG Tablet",
    "Twirla",
    "Tyrvava",
    "V-GO",
    "Vraylar",
    "Vyvanse",
    "Veozah",
    "Vevye",
    "Voquezna",
    "Voquezna Triple Pack",
    "Wegovy",
    "Wegovy 0.25MG/0.5ML Injection",
    "Winlevi",
    "Xhance",
    "Xhance 93MCG",
    "Xiidra",
    "Xifixan",
    "Yupelri",
    "Zoryve",
    "Zoryve 0.3%",
    "Zoryve FOAM",
    "Zavzpret",
    "Zepbound",
    "Akilef",
    "Alprazolam Tablets",
    "Diazepam Tablets",
    "Diclofenac Sodium 3% Gel",
    "Vascepa",
];

export const insurances: string[] = [
    "Anthem",
    "Aetna",
    "BCBS",
    "BCBSM",
    "Blue Cross Blue Sheild of California",
    "Benecard",
    "Caremark",
    "CVS",
    "EmblemHealth",
    "Emblem health",
    "Express",
    "Fidelis",
    "Fidelis Care Commericial",
    "Horizon",
    "Horizon Blue Cross Blue Shield",
    "Blue Cross Blue Shield",
    "Blue Cross Blue Shield of Michigan",
    "Blue Cross Blue Shield of Minnesota",
    "Blue Cross Blue Shield of Massachsetts",
    "Horizon New Jersey Health",
    "OptumRx",
    "SmithRx",
    "Navitus",
    "Cigna",
    "United health care",
    "Capital Rx"
];
